controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_drive:
      type: "ackermann_steering_controller/AckermannSteeringController"

      front_wheel_track: 0.7  # distance between front wheels
      rear_wheel_track: 0.7   # distance between rear wheels
      front_wheels_radius: 20  # e.g., front wheel radius in meters
      rear_wheels_radius: 0.14   # rear wheel radius in meters
      wheel_separation: 0.8
      front_steering: false
      steering_wheel_names: ["rear_left_wheel", "rear_right_wheel"]
      drive_wheel_names: ["front_left_wheel", "front_right_wheel"]


    

